### PR TITLE
Refactor: Convert README.rst to README.md

### PR DESCRIPTION
**Pull request by JTaeuber**
## Motivation
Relates to https://github.com/caas-team/new-pykube/issues/10.

## Changes
* Changed the README.rst file to a markdown file and changed a few descriptions. I left the ```pip install pykube-ng``` since we don`t have a package to install yet.
* Changed a few values in the pyproject.toml

## TODO

- [x] I've assigned myself to this PR

### CODE REVIEW

**Comment by JTaeuber** [comment]
There are still references to pykube-ng in the python code. This should be taken care of next.

**Comment by Fovty** [comment]
In order to keep track, here are the remaining references, right?

- `README.md`
- `docs/index.rst`
- `docs/users.rst`
- `docs/write-an-operator.rst`
- `pykube/config.py`
- `pykube/http.py`
- `pykube/test_config.py`
- `pykube/test_http.py`

**Review by Fovty — APPROVED** [review]
LGTM

**Comment by JTaeuber** [comment]
> In order to keep track, here are the remaining references, right?
> 
> * `README.md`
> * `docs/index.rst`
> * `docs/users.rst`
> * `docs/write-an-operator.rst`
> * `pykube/config.py`
> * `pykube/http.py`
> * `pykube/test_config.py`
> * `pykube/test_http.py`

Pretty much. Just keep in mind that it's `docs/howtos/write-an-operator.rst` to avoid confusion.

**Pull request merged**
