### PR TITLE
chore: clean repo

### PR DESCRIPTION
**Pull request by JTaeuber**
## Motivation
I started doing a little cleanup like in https://github.com/caas-team/py-kube-downscaler/pull/112.

## Changes
* Made pre-commit config usable
* Removed not needed files
* Formatted files
* Adjusted a few parameters
* Bumped version number for new release

## Tests done
pre-commit and pytest pass

## TODO

- [x] I've assigned myself to this PR

### CODE REVIEW

**Review by jonathan-mayer — APPROVED** [review]
LFineTM

**Comment by Fovty** [comment]
@JTaeuber We should bump python version in the workflows too (similar to [this](https://github.com/caas-team/py-kube-downscaler/pull/122)), and maybe also the classifiers in pyproject.toml

**Review by Fovty — COMMENTED** [review]
Rest looks fine

**Comment by JTaeuber** [comment]
forgot about the worflows, good call 👍

**Comment by Fovty** [comment]
Yeah, exactly, will look clean on [pypi ](https://pypi.org/project/new-pykube/) then

**Review by Fovty — APPROVED** [review]
LGTM👍

**Pull request merged**
